# https://github.com/marketplace/actions/newman-action
on:
  push:
    branches:
      - Azure
  workflow_dispatch:
jobs:
  newman:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:          
          collection: Restricted Backed.postman_collection.json    