# https://github.com/marketplace/actions/newman-action
name: Newman Run
on:
  push:
    branches:
      - Azure

jobs:
  - name: Run a one-line script
    run: echo Hello, world!
  newman:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:          
          collection: Restricted Backed.postman_collection.json    